### ISSUE TITLE
Unexpected error fetching nextdns data: 'DNS-over-QUIC'

### ISSUE THREAD

**Issue by johan-de-jong** [bieniu/ha-nextdns#1]
The NextDNS integration won't start for me. This is the relevant logging I found:

<pre>
2022-06-17 19:31:30 ERROR (MainThread) [custom_components.nextdns] Unexpected error fetching nextdns data: 'DNS-over-QUIC'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/nextdns/__init__.py", line 199, in _async_update_data
    return await self.nextdns.get_analytics_protocols(self.profile_id)
  File "/usr/local/lib/python3.9/site-packages/nextdns/__init__.py", line 122, in get_analytics_protocols
    **{MAP_PROTOCOLS[item["protocol"]]: item["queries"] for item in resp}
  File "/usr/local/lib/python3.9/site-packages/nextdns/__init__.py", line 122, in <dictcomp>
    **{MAP_PROTOCOLS[item["protocol"]]: item["queries"] for item in resp}
KeyError: 'DNS-over-QUIC'

2022-06-17 19:31:30 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Calypso' for nextdns integration not ready yet: 'DNS-over-QUIC'; Retrying in background
2022-06-17 19:31:30 ERROR (MainThread) [custom_components.nextdns] Unexpected error fetching nextdns data: 'relayed'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/nextdns/__init__.py", line 151, in _async_update_data
    return await self.nextdns.get_analytics_status(self.profile_id)
  File "/usr/local/lib/python3.9/site-packages/nextdns/__init__.py", line 86, in get_analytics_status
    **{MAP_STATUS[item["status"]]: item["queries"] for item in resp}
  File "/usr/local/lib/python3.9/site-packages/nextdns/__init__.py", line 86, in <dictcomp>
    **{MAP_STATUS[item["status"]]: item["queries"] for item in resp}
KeyError: 'relayed'</pre>

**Comment by bieniu** [comment]
Hi. Thanks for the report. The issue should be fixed by this commit https://github.com/bieniu/ha-nextdns/commit/1b9a0442fbfc246d32b79bd3f0f8636e34d1eed1 Please update the component.

Could you add this to your `configuration.yaml` file, restart HA and show me the log (before sharing, scrub the log of NextDNS  profile IDs and IP addresses)?
```yaml
logger:
  default: warning
  logs:
    nextdns: debug
    custom_components.nextdns: debug
```

**Comment by johan-de-jong** [comment]
The latest commit starts without problem. Thanks.

Here is the requested scrubbed logging:

<pre>
2022-06-18 12:21:46 DEBUG (MainThread) [nextdns] Initializing with API Key: aaaaaaaaaa...
2022-06-18 12:21:46 DEBUG (MainThread) [nextdns] Requesting https://api.nextdns.io/profiles, method: get
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Response status: 200
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Response: {'data': [{'id': '123456', 'fingerprint': 'fpc4c290f42cbcc5b6', 'name': 'Home'}, {'id': '8fec92', 'fingerprint': 'fpfdc3e200f7477872', 'name': 'Device'}]}
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Requesting https://123456.test.nextdns.io, method: get
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Requesting https://api.nextdns.io/profiles/123456/analytics/dnssec, method: get
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Requesting https://api.nextdns.io/profiles/123456/analytics/encryption, method: get
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Requesting https://api.nextdns.io/profiles/123456/analytics/ipVersions, method: get
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Requesting https://api.nextdns.io/profiles/123456/analytics/protocols, method: get
2022-06-18 12:21:52 DEBUG (MainThread) [nextdns] Requesting https://api.nextdns.io/profiles/123456/analytics/status, method: get
2022-06-18 12:21:54 DEBUG (MainThread) [nextdns] Response status: 200
2022-06-18 12:21:54 DEBUG (MainThread) [nextdns] Response: {'data': [{'validated': False, 'queries': 789969}, {'validated': True, 'queries': 27872}], 'meta': {'pagination': {'cursor': None}}}
2022-06-18 12:21:54 DEBUG (MainThread) [custom_components.nextdns] Finished fetching nextdns data in 1.575 seconds (success: True)
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response status: 200
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response: {'data': [{'protocol': 'DNS-over-HTTPS', 'queries': 878092}, {'protocol': 'DNS-over-QUIC', 'queries': 11131}], 'meta': {'pagination': {'cursor': None}}}
2022-06-18 12:21:56 DEBUG (MainThread) [custom_components.nextdns] Finished fetching nextdns data in 4.120 seconds (success: True)
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response status: 200
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response: {'data': [{'status': 'default', 'queries': 810984}, {'status': 'blocked', 'queries': 71297}, {'status': 'allowed', 'queries': 6857}, {'status': 'relayed', 'queries': 85}], 'meta': {'pagination': {'cursor': None}}}
2022-06-18 12:21:56 DEBUG (MainThread) [custom_components.nextdns] Finished fetching nextdns data in 4.115 seconds (success: True)
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response status: 200
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response: {'data': [{'encrypted': True, 'queries': 889223}], 'meta': {'pagination': {'cursor': None}}}
2022-06-18 12:21:56 DEBUG (MainThread) [custom_components.nextdns] Finished fetching nextdns data in 4.126 seconds (success: True)
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response status: 200
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response: {'data': [{'version': 4, 'queries': 889223}], 'meta': {'pagination': {'cursor': None}}}
2022-06-18 12:21:56 DEBUG (MainThread) [custom_components.nextdns] Finished fetching nextdns data in 4.125 seconds (success: True)
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response status: 200
2022-06-18 12:21:56 DEBUG (MainThread) [nextdns] Response: {'status': 'unconfigured', 'resolver': 'w.x.y.z', 'ecs': 'w.x.y.z/24/0', 'srcIP': 'w.x.y.z', 'server': 'xxxx-yyy-1'}
2022-06-18 12:21:56 DEBUG (MainThread) [custom_components.nextdns] Finished fetching nextdns data in 4.218 seconds (success: True)
</pre>

**Comment by bieniu** [comment]
Thanks for the log, you have a completely different configuration than mine so it helped me a lot.
