### ISSUE TITLE
One out of three NextDNS configs fails to load

### ISSUE THREAD

**Issue by lancer73** [bieniu/ha-nextdns#4]
I have three sites configured in NextDNS under the same account (with the same API key)

Two of them load flawlessly, one gives an error message “ Retrying setup: 'TCP'”.

Tried restarting HA and removing and re-adding this site (it was the first one added), but no luck so far.

I had a script reading NextDNS and pushing the data to HA. When querying NextDNS this site works just fine and returns normal data.

Error in the logfile
2022-07-06 21:25:28 ERROR (MainThread) [custom_components.nextdns] Unexpected error fetching nextdns data: 'TCP'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/nextdns/__init__.py", line 205, in _async_update_data
return await self.nextdns.get_analytics_protocols(self.profile_id)
File "/usr/local/lib/python3.9/site-packages/nextdns/__init__.py", line 193, in get_analytics_protocols
**{MAP_PROTOCOLS[item["protocol"]]: item["queries"] for item in resp}
File "/usr/local/lib/python3.9/site-packages/nextdns/__init__.py", line 193, in <dictcomp>
**{MAP_PROTOCOLS[item["protocol"]]: item["queries"] for item in resp}
KeyError: 'TCP'

**Comment by bieniu** [comment]
Please update the integration.

**Comment by lancer73** [comment]
Fixed! That was fast.

Thanks!

Kind regards,
Roel
________________________________
